 CountVectorizer means breaking down a sentence or any text into words by performing preprocessing tasks like converting all words to lowercase, thus removing special characters.

In [2]:
import nltk
nltk.download('punkt')   #Another way to download

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
import nltk
# nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [5]:
#cleaning the texts

import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
ps=PorterStemmer()
wordnet=WordNetLemmatizer()
sentences=nltk.sent_tokenize(paragraph)
sentences
len(sentences)

31

In [5]:
corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    print(review)
    #replace characters other than [a-z] and (A-Z) with spaces
    review=review.lower()#convert to lowercase
    review=review.split()# split using space(list of words)
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    #check whether stop word  or not
    review=' '.join(review)# join the preprocessed words
    corpus.append(review)# append the content
print(corpus)#print  the preprocessed content

I have three visions for India 
In      years of our history  people from all over                 the world have come and invaded us  captured our lands  conquered our minds 
From Alexander onwards  the Greeks  the Turks  the Moguls  the Portuguese  the British                 the French  the Dutch  all of them came and looted us  took over what was ours 
Yet we have not done this to any other nation 
We have not conquered anyone 
We have not grabbed their land  their culture                  their history and tried to enforce our way of life on them 
Why 
Because we respect the freedom of others That is why my                 first vision is that of freedom 
I believe that India got its first vision of                 this in       when we started the War of Independence 
It is this freedom that                we must protect and nurture and build on 
If we are not free  no one will respect us 
My second vision for India s development 
For fifty years we have been a developing nation

In [6]:
#creating the bag of words model(into vectors)
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus).toarray()
print(X)
X.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(31, 113)

In [7]:
cv.get_feature_names_out()

array(['achiev', 'alexand', 'also', 'among', 'anyon', 'area', 'assur',
       'believ', 'brahm', 'british', 'build', 'came', 'captur', 'career',
       'close', 'come', 'confid', 'conquer', 'consid', 'cultur', 'dept',
       'develop', 'dhawan', 'done', 'dr', 'dutch', 'econom', 'enforc',
       'fall', 'father', 'fifti', 'first', 'fortun', 'four', 'free',
       'freedom', 'french', 'gdp', 'global', 'go', 'good', 'got', 'grab',
       'great', 'greek', 'growth', 'hand', 'histori', 'incorrect',
       'independ', 'india', 'invad', 'lack', 'land', 'level', 'life',
       'loot', 'lucki', 'materi', 'mileston', 'militari', 'mind', 'mogul',
       'must', 'nation', 'nuclear', 'nurtur', 'one', 'onward', 'opportun',
       'other', 'peopl', 'percent', 'portugues', 'poverti', 'power',
       'prakash', 'professor', 'protect', 'rate', 'recognis', 'reliant',
       'respect', 'sarabhai', 'satish', 'second', 'see', 'self', 'space',
       'stand', 'start', 'strength', 'strong', 'succeed', 'term',

## vectorisation in spam data

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
from nltk.stem import WordNetLemmatizer
wl=WordNetLemmatizer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [7]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [12]:
messages=pd.read_csv("C:/Users/user/Desktop/python/SMSSpamCollection.unknown",sep='\t',names=['label','message'])
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [21]:
#data cleaning and preprocessing
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    #replace characters other than [a-z] and (A-Z) with spaces
    review=review.lower()#convert tolowercase
    review=review.split()# split using space(list of words)
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    #check whether stop word  or not
    review=' '.join(review)# join the preprocessed words
    corpus.append(review)# append the content
print(corpus)#print  the preprocessed content

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat', 'ok lar joke wif u oni', 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli', 'u dun say earli hor u c alreadi say', 'nah think goe usf live around though', 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv', 'even brother like speak treat like aid patent', 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun', 'winner valu network custom select receivea prize reward claim call claim code kl valid hour', 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free', 'gonna home soon want talk stuff anymor tonight k cri enough today', 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info', 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw', 'search right word thank breather promis wont 

In [23]:
#creating the bag of words model

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(corpus).toarray()
y=pd.get_dummies(messages['label'])
y=y.iloc[:,1].values


In [24]:
#train test split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=0)

In [25]:
#training model using bayes classifier

from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(x_train,y_train)
y_pred=spam_detect_model.predict(x_test)

In [26]:
y_pred

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [27]:
from sklearn.metrics import confusion_matrix
confusion_m=confusion_matrix(y_test,y_pred)
confusion_m

array([[940,  15],
       [  8, 152]], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.979372197309417

## Data financial sentimental

In [22]:
import pandas as pd
from sklearn import metrics
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wl=WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [29]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [30]:
data=pd.read_csv('Financial sentimental analysis.csv')
data

Sentence Sentiment
0     The GeoSolutions technology will leverage Bene...  positive
1     $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2     For the last quarter of 2010 , Componenta 's n...  positive
3     According to the Finnish-Russian Chamber of Co...   neutral
4     The Swedish buyout firm has sold its remaining...   neutral
...                                                 ...       ...
5837  RISING costs have forced packaging producer Hu...  negative
5838  Nordic Walking was first used as a summer trai...   neutral
5839  According shipping company Viking Line , the E...   neutral
5840  In the building and home improvement trade , s...   neutral
5841  HELSINKI AFX - KCI Konecranes said it has won ...  positive

[5842 rows x 2 columns]

In [32]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Sentiment']=le.fit_transform(data['Sentiment'])
data

Sentence  Sentiment
0     The GeoSolutions technology will leverage Bene...          2
1     $ESI on lows, down $1.50 to $2.50 BK a real po...          0
2     For the last quarter of 2010 , Componenta 's n...          2
3     According to the Finnish-Russian Chamber of Co...          1
4     The Swedish buyout firm has sold its remaining...          1
...                                                 ...        ...
5837  RISING costs have forced packaging producer Hu...          0
5838  Nordic Walking was first used as a summer trai...          1
5839  According shipping company Viking Line , the E...          1
5840  In the building and home improvement trade , s...          1
5841  HELSINKI AFX - KCI Konecranes said it has won ...          2

[5842 rows x 2 columns]

In [33]:
#data cleaning and preprocessing
corpus=[]
for i in range(0,len(data)):
    review=re.sub('[^a-zA-Z]',' ',data['Sentence'][i])
    #replace characters other than [a-z] and (A-Z) with spaces
    review=review.lower()#convert tolowercase
    review=review.split()# split using space(list of words)
    review=[wl.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    #check whether stop word  or not
    review=' '.join(review)# join the preprocessed words
    corpus.append(review)# append the content
print(corpus)#print  the preprocessed content

['geosolutions technology leverage benefon gps solution providing location based search technology community platform location relevant multimedia content new powerful commercial model', 'esi low bk real possibility', 'last quarter componenta net sale doubled eur eur period year earlier moved zero pre tax profit pre tax loss eur', 'according finnish russian chamber commerce major construction company finland operating russia', 'swedish buyout firm sold remaining percent stake almost eighteen month taking company public finland', 'spy surprised see green close', 'shell billion bg deal meet shareholder skepticism', 'ssh communication security corp stock exchange release october pm company update full year outlook estimate result remain loss full year', 'kone net sale rose year year first nine month', 'stockmann department store total floor space square metre stockmann investment project price tag eur million', 'circulation revenue increased finland sweden', 'sap q disappoints software li

In [36]:
#creating the bag of words model

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(corpus).toarray()

y=data.iloc[:,1].values

In [37]:
y

array([2, 0, 2, ..., 1, 1, 2])

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=5)

In [49]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [58]:
y_pred=lr.predict(x_test)
y_pred

array([1, 2, 2, ..., 1, 1, 2])

In [59]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,y_test)
cm

array([[ 92,  36,   5],
       [ 77, 552,  40],
       [ 14,  16, 337]], dtype=int64)

In [60]:
from sklearn import metrics
score=accuracy_score(y_pred,y_test)
score

0.8391787852865698

In [61]:
# knn
from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(x_train,y_train)

y_pred=lr.predict(x_test)
y_pred

array([1, 2, 2, ..., 1, 1, 2])

In [62]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,y_test)
cm

array([[ 92,  36,   5],
       [ 77, 552,  40],
       [ 14,  16, 337]], dtype=int64)

In [63]:
from sklearn import metrics
score=accuracy_score(y_pred,y_test)
score

0.8391787852865698

In [67]:

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(corpus).toarray()

y=data.iloc[:,1].values

In [90]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=5)

In [91]:
#training model using bayes classifier

from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(x_train,y_train)
y_pred=spam_detect_model.predict(x_test)
y_pred

array([1, 2, 2, ..., 1, 1, 1])

In [92]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,y_test)
cm

array([[ 74,  74,  25],
       [ 71, 476, 101],
       [ 38,  54, 256]], dtype=int64)

In [93]:
from sklearn import metrics
score=accuracy_score(y_pred,y_test)
score

0.6894781864841745

In [94]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)


DecisionTreeClassifier()

In [95]:
y_pred=dtc.predict(x_test)
y_pred

array([1, 2, 2, ..., 1, 1, 1])

In [96]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[ 37, 104,  42],
       [116, 413,  75],
       [ 29,  99, 254]], dtype=int64)

In [97]:
from sklearn import metrics
score=accuracy_scorecy_scoreuracy_scoreuracy_scoreuracy_score(y_pred,y_test)
score

0.602224123182207